# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_About.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_About(object):
    def setupUi(self, About):
        About.setObjectName("About")
        About.setWindowModality(QtCore.Qt.WindowModal)
        About.resize(300, 300)
        About.setMinimumSize(QtCore.QSize(300, 300))
        About.setMaximumSize(QtCore.QSize(300, 300))
        self.titleLabel = QtWidgets.QLabel(About)
        self.titleLabel.setGeometry(QtCore.QRect(10, 10, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.titleLabel.setFont(font)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.versionLabel = QtWidgets.QLabel(About)
        self.versionLabel.setGeometry(QtCore.QRect(10, 40, 281, 21))
        self.versionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.versionLabel.setObjectName("versionLabel")
        self.aboutdetailLabel = QtWidgets.QLabel(About)
        self.aboutdetailLabel.setGeometry(QtCore.QRect(20, 100, 261, 91))
        self.aboutdetailLabel.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.aboutdetailLabel.setWordWrap(True)
        self.aboutdetailLabel.setObjectName("aboutdetailLabel")
        self.copyrightLabel = QtWidgets.QLabel(About)
        self.copyrightLabel.setGeometry(QtCore.QRect(20, 230, 261, 61))
        self.copyrightLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.copyrightLabel.setWordWrap(True)
        self.copyrightLabel.setObjectName("copyrightLabel")
        self.aboutLabel = QtWidgets.QLabel(About)
        self.aboutLabel.setGeometry(QtCore.QRect(10, 80, 281, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.aboutLabel.setFont(font)
        self.aboutLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.aboutLabel.setObjectName("aboutLabel")

        self.retranslateUi(About)
        QtCore.QMetaObject.connectSlotsByName(About)

    def retranslateUi(self, About):
        _translate = QtCore.QCoreApplication.translate
        About.setWindowTitle(_translate("About", "Về phần mềm"))
        self.titleLabel.setText(_translate("About", "ĐỒ ÁN SOCKET"))
        self.versionLabel.setText(_translate("About", "Version 1.0"))
        self.aboutdetailLabel.setText(_translate("About", "Chương trình mô phỏng ứng dụng trực tuyến gồm một server và nhiều client. Server sẽ lưu trữ thông tin giá vàng giúp client có thể tra cứu. Mọi quá trình client đăng nhập, client đăng xuất, .... đều được thể hiện trên màn hình của server. Chương trình được viết trên ngôn ngữ Python."))
        self.copyrightLabel.setText(_translate("About", "Copyright © 2021 by Nguyen Minh Tri (20120219), Ton Cao Thien Trung (20120227) and Hoang Duc Nhat Minh (20120328). All rights reserved."))
        self.aboutLabel.setText(_translate("About", "Về chương trình"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    About = QtWidgets.QDialog()
    ui = Ui_About()
    ui.setupUi(About)
    About.show()
    sys.exit(app.exec_())
